# Taskfile.yml

version: '3'

vars:
  ProjectName:
    description: "The name of the project"
    default: "my_project"
  DBVersion:
    description: "The version of the database"
    default: "mysql:8"
  SecretKey:
    description: "The secret key for the project"
    default: "defaultsecret"

tasks:
  build:
    desc: "Build the CraftyPanda CLI tool"
    cmds:
      - go build -o craftypanda
    silent: false

  run:
    desc: "Run the CraftyPanda CLI tool with Cobra and Viper"
    cmds:
      - ./craftypanda generate --name {{.ProjectName}} --db {{.DBVersion}} --secret {{.SecretKey}}
    silent: false

  generate:
    desc: "Generate project files dynamically using text/template"
    cmds:
      - ./craftypanda generate --name {{.ProjectName}} --db {{.DBVersion}} --secret {{.SecretKey}}
    silent: false

  test:
    desc: "Run tests for CraftyPanda"
    cmds:
      - go test ./...
    silent: false

  clean:
    desc: "Clean up generated files and build artifacts"
    cmds:
      - rm -f craftypanda
      - rm -rf generated-project
    silent: false

  help:
    desc: "Display help for available tasks"
    cmds:
      - task --list
    silent: false
