# Taskfile.yml

version: '3'

vars:
  ProjectName: "my_project"
  DBVersion: "mysql"
  ProjectType: "django"

silent: false

tasks:
  build:
    desc: "Build the P4ndaFrame CLI tool"
    cmds:
      - go build -o p4ndaframe
    sources: 
      - cmd/*

  run:
    deps: [build]
    desc: "Run the P4ndaFrame CLI tool"
    cmds:
      - ./p4ndaframe create -n {{.ProjectName}} -d {{.DBVersion}} -p {{.ProjectType}}

  clean:
    desc: "Clean up generated files and build artifacts"
    cmds:
      - rm -f p4ndaframe
      - rm -rf my_project
      - rm -rf .task/checksum/build

  help:
    desc: "Display help for available tasks"
    cmds:
      - task --list
    silent: true

  default:
    desc: "The task that runs when a command is not specified"
    cmds:
      - task: help